### ISSUE TITLE
モーダルウィンドウモジュールの追加

### ISSUE THREAD

**Issue by neocryses** [ritaworks/s3-template#16]
要望が上がったので追加予定。

**Comment by tanpopo1225** [comment]
とりあえず何のプラグインをを入れるか決めませんか？

**Comment by abe-work** [comment]
[iziModal.js](http://izimodal.marcelodolce.com/)でtanpopo1225さんお願いします。

**Comment by neocryses** [comment]
#37 をもってクローズとします。
