### ISSUE TITLE
フォントサイズのクラスを生成する記述をmixin化する

### ISSUE THREAD

**Issue by tanpopo1225** [ritaworks/s3-template#34]

**Comment by tajimakento** [comment]
どういった意味でmixin化するのでしょうか？
理解が及ばずすみません。

**Comment by tanpopo1225** [comment]
sassの記述量削減の意味合いがあります。
s3-template/user/theme/THEME-NAME/media/sass/core/mixins/_utility.scss及び、
s3-template/user/theme/THEME-NAME/media/sass/core/_class.scssを見ていただければと思います。
