### ISSUE TITLE
sass/module/button/内のクラスがeditor.scssに書かれているクラスと被っている

### ISSUE THREAD

**Issue by tanpopo1225** [ritaworks/s3-template#36]
sass/module/button/内のクラス名を書き換えて頂くか、
そもそも使い方が違うのであれば、これからこちらを使う及びテーブル用のファイルを作成する。

**Comment by neocryses** [comment]
moduleは%で指定するプレースホルダークラスとして作成するかmixinとするのはどうでしょうか？

**Comment by tanpopo1225** [comment]
それで行きましょう
pager.scssの変更も必要になりますね
