### ISSUE TITLE
line-heightクラスの追加

### ISSUE THREAD

**Issue by neocryses** [ritaworks/s3-template#46]
デザイン上、ページ内で1.5, 1.8等複数のline-heightが使われているのを見受けられるため必要なのではと思います。
また、line-height: 1; はボタン要素等において便利かと思います。

**Comment by tajimakento** [comment]
1~2までは0.1刻みであっても良いですね。

あっているかわかりませんが、以下のような感じでしょうか？
クラス名があまり良いのが浮かびません。

_utility.scss
```
// line-heightクラスの生成
@mixin lineheight($sufix: "") {
  @for $i from 1 through 2 {
    .lh#{$i * 0.1}#{$sufix} {
      line-height: #{$i * 0.1} !important;
    }
  }
}
```

**Comment by ritaworks-n** [comment]
念のため3くらいまで欲しいです
というか使うことがあったので
