### ISSUE TITLE
bootstrapのようにデフォルトのinputにcss設定しておきたい。

### ISSUE THREAD

**Issue by tajimakento** [ritaworks/s3-template#51]
どうでしょうか？

**Comment by neocryses** [comment]
私は良いと思います。
できれば各ブラウザによって変動するcss設定（-webkit-appearance等）をリセットするクラスもあれば便利なのかなと思います。

**Comment by tanpopo1225** [comment]
何種類か用意できるといいのかなと思います。
あと、デフォルトのデザイン等の作成は必要でしょうか？

**Comment by tajimakento** [comment]
種類はとりあえずいらないです。
デフォルトのデザインはbootstrapをパクりましょう。
http://getbootstrap.com/2.3.2/base-css.html#forms

ちなみにCSSを付与するのはtextareaとtype="text"とselectだけで良いと思います。

**Comment by tanpopo1225** [comment]
buttonタグのborder
すべてのinput関係のoutlineをデフォルトで消していただけると助かります。
