### ISSUE TITLE
README.mdの更新

### ISSUE THREAD

**Issue by neocryses** [ritaworks/s3-template#53]
[README.md](https://github.com/natrin/s3-template/blob/bd163c1/README.md)の内容が古く、Wikiの内容ともかぶっているので書き換えたほうが良いと思います。
そこでなんですけど、内容を何にするかの意見などありませんでしょうか？

**Comment by tajimakento** [comment]
以下だけで良いかと思いますが、どうでしょうか。
・CSS設計
・対応ブラウザ（wikiからもってきる）
・ディレクトリの概要（wikiからもってきる）

**Comment by neocryses** [comment]
@tajimakento ご意見ありがとうございます。  
自分も上記内容で良いかと思います。   
「対応ブラウザ」と「ディレクトリ概要」に関しては更新時に二度手間にならないよう、Wikiページへリンクするまでに留めておいても良いかもしれません

**Comment by tanpopo1225** [comment]
自作プラグインの説明を載せるのはどうでしょうか？

**Comment by tajimakento** [comment]
自作プラグインとは具体的にどのような内容でしょうか？

**Comment by tanpopo1225** [comment]
user/theme/THEME-NAME/media/js/module内のjsです。
オプション等の共有が曖昧だったりするので一箇所に集めた方がいいのではと思いました。
