### ISSUE TITLE
slider pro のプラグイン追加

### ISSUE THREAD

**Issue by tanpopo1225** [ritaworks/s3-template#65]
トップページでほとんどの確率でスライダーが出てきているのでcdn等で追加しても良いのでは無いでしょうか？

**Comment by naaaaagai** [comment]
押したときに消える感じが解消されるならいいと思います
個人的にはパッと消える感じあんまり好きじゃないです
http://www.wanpaku.org/index.html

**Comment by tanpopo1225** [comment]
slickなどのプラグインの方がいい感じですか？
