### ISSUE TITLE
core.scssの設定

### ISSUE THREAD

**Issue by tanpopo1225** [ritaworks/s3-template#68]
aのfocus時のoutlineの消去やtextareaのline-heightなど見直した方が良いのではないでしょうか？

**Comment by tanpopo1225** [comment]
imgにデフォルトでmax-width:100%を入れてもいいんじゃないでしょうか?byあべ

**Comment by tajimakento** [comment]
aのfocus時のoutlineは消去しても良いかと思いますが、textareaのline-heightは$base-line-heightと同じでもよいかと思います。

**Comment by tanpopo1225** [comment]
他意見がなければ以下の内容を今週末に対応します。

#対応するもの
## core.scss
before,afterにdisplay: inline-blockを設定
html input[type="button"]などのhtml削除
input関係以外のfocus時のoutline削除
imgにmax-width: 100%設定
labelタグへのdisplay: inline-block;設定

## core.scss以外
style.scssなどよく使うものに@charset 'UTF-8'設定
common.jsリファクタリング
fadeの挙動を.2sにする
flex関係のクラス、mixinを追加する

**Comment by tanpopo1225** [comment]
common.jsのリファクタリングは一旦保留にします
