### ISSUE TITLE
font-weightのクラス

### ISSUE THREAD

**Issue by tanpopo1225** [ritaworks/s3-template#72]
現状、.normal及び.boldしか用意されていませんが、noto sans等のこと考えて.midium等のクラスを用意したようがいいと思うのですがどうでしょうか？

**Comment by tajimakento** [comment]
OK

**Comment by tajimakento** [comment]
mediumだけでなく全てのweight用意しましょう！
クラス名が.midium.thinとかになるようにしてください
参考：http://on-ze.com/demo/font-noto/

**Comment by tajimakento** [comment]
また、終了したら以下のようにwikiにも記載してください。
https://github.com/ritaworks/s3-template/wiki/%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%81%AB%E7%B5%84%E3%81%BF%E8%BE%BC%E3%81%BE%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%82%AF%E3%83%A9%E3%82%B9

またその際、ritaworks/s3-templateのwikiには編集権限がないはずなのでコミットメッセージに
自分のフォークしたもののwikiに書いてurl送ってください。
