### ISSUE TITLE
letter-spacingについて

### ISSUE THREAD

**Issue by tanpopo1225** [ritaworks/s3-template#73]
_setting.scssにline-heightの設定等はありますが、letter-spacingの設定はありません。
追加してはどうでしょうか？
あとletter-spacingのクラスを用意してはどうでしょうか？

**Comment by ritaworks-n** [comment]
_OK_

**Comment by tajimakento** [comment]
終了したら以下のようにwikiにも記載してください。
https://github.com/ritaworks/s3-template/wiki/%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%81%AB%E7%B5%84%E3%81%BF%E8%BE%BC%E3%81%BE%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%82%AF%E3%83%A9%E3%82%B9

またその際、ritaworks/s3-templateのwikiには編集権限がないはずなのでコメントで
自分のフォークしたもののwikiに書いたurl送ってください。
