### ISSUE TITLE
canonical+faviconのコメントアウトはいらないのでは

### ISSUE THREAD

**Issue by tajimakento** [ritaworks/s3-template#77]
組み込み時にコメントアウトを取るのが面倒なので...
意図があればどなたか教えてください。

**Comment by ritaworks-n** [comment]
理由としては単純にコメントアウトしとかないと独自タグが文字列として表示されてしまうのでコメントアウトしてます。
組み込み時に各々で追加するか、コメントアウトするかのどっちかだと思います。

ただそれはfaviconの方だけなのでcanonicalに関してはコメントアウト外しちゃっていいと思います。

**Comment by tajimakento** [comment]
ではcanonicalだけコメントアウト外しましょうか
