### ISSUE TITLE
ハンバーガーメニューのスタイル

### ISSUE THREAD

**Issue by tanpopo1225** [ritaworks/s3-template#81]
ハンバーガーメニューのスタイルのベースを用意するのはどうでしょうか？
https://www.nxworld.net/tips/12-css-hamburger-menu-active-effect.html

**Comment by tajimakento** [comment]
使いたい人が、コピペで使えば良いのではないでしょうか。
htmlとセットでテンプレにないと誰も使わないような気がするので...

wikiに使い方の説明書くなら追加しても良いかもしれませんが

**Comment by tanpopo1225** [comment]
本日中に他のコメントがなければこのissueはcloseします。

**Comment by tanpopo1225** [comment]
コメントでなさそうなのでcloseします
